#!/bin/bash

SLURM_CFG_PATH=~/.config/snakemake
if [ $# -eq 1 ] ; then
    SLURM_CFG_PATH=$SLURM_CFG_PATH/$1
else
    SLURM_CFG_PATH=$SLURM_CFG_PATH/slurm
fi

mkdir -p $SLURM_CFG_PATH
cp -rf ./slurm/* $SLURM_CFG_PATH
